# fly.toml app configuration file generated for reactivities-zb on 2023-11-24T00:45:02+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-zb"
primary_region = "sin"

[build]
  image = "zakariabijoy/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="zakariabijoy"
  Cloudinary__APIKey="372896596436432"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
